export const IS_LOADING = 'IS_LOADING';
export const IS_COMPLETE = 'IS_COMPLETE';


export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const USER_CREATE_REQUEST_SUCCESSFUL = 'USER_CREATE_REQUEST_SUCCESSFUL';
export const USER_CREATE_REQUEST_FAILED = 'USER_CREATE_REQUEST_FAILED';

export const USER_GET_REQUEST_SUCCESSFUL = 'USER_GET_REQUEST_SUCCESSFUL';
export const USER_GET_REQUEST_FAILED = 'USER_GET_REQUEST_FAILED';

export const USER_UPDATE_REQUEST_SUCCESSFUL = 'USER_UPDATE_REQUEST_SUCCESSFUL';
export const USER_UPDATE_REQUEST_FAILED = 'USER_UPDATE_REQUEST_FAILED';

export const USER_GET_ALL_REQUESTS_SUCCESSFUL = 'USER_GET_ALL_REQUESTS_SUCCESSFUL';
export const USER_GET_ALL_REQUESTS_FAILED = 'USER_GET_ALL_REQUESTS_FAILED';

export const NETWORK_ERROR = 'NETWORK_ERROR';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';

export const CLEAR_VALIDATION_ERROR = 'CLEAR_VALIDATION_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_REQUEST = 'CLEAR_REQUEST';
